language: python
sudo: false
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

install:
 - "pip install -r requirements.txt"

script:
  - "pytest tests/"

notifications:
  email:
    on_success: change
    on_failure: always
